### ISSUE TITLE
Navigation not working

### ISSUE THREAD

**Issue by kilianso** [consoledotdev/home#119]
Hey👋 Cool site. Just wanted to let you know that the navigation of your website is not clickable. Tested on Safari, iOS15.

**Comment by davidmytton** [comment]
Righto, thanks. Sounds like something changed in iOS 15. It's working fine on desktop in Safari 15.0 and on iOS 14. We'll investigate.

**Comment by kilianso** [comment]
https://user-images.githubusercontent.com/15088651/137614173-86c17c71-3824-4ee6-94e8-9204c343917f.MOV

Here's a screerecording on iOS 15.0.1

Seems like only the main navigation items are not clickable. On the blog the navigation works.

**Comment by davidmytton** [comment]
Thanks @kilianso for the video.

@morekid I've been able to reproduce this on a browser testing platform that now has iOS15. I'll send you an invite.
