### ISSUE TITLE
Usability on very wide screens

### ISSUE THREAD

**Issue by davidmytton** [consoledotdev/home#23]
@morekid can you have a play around with optimising the site for very wide screens please? Personally I find it odd that you would browse the web with a window the width of a very large display, but some people do, and the layout doesn't scale that well.

I think we want to keep the fixed width of the text - it's better for readability - but maybe it needs to be centered? The menu right aligned is also not ideal for such large displays because it's so far away.

Worth some experiments.

![image](https://user-images.githubusercontent.com/117833/111747222-f86fbe00-8886-11eb-900a-a8fcd35a8cc0.png)

**Comment by morekid** [comment]
https://github.com/consoledotdev/home/pull/27 adds an improvement to this by introducing a max width.

Content width will have to follow a max line length so we can explore these instead:
- TOC
- Side navigation with articles index.

**Comment by davidmytton** [comment]
We can close this issue as the main problem is solved. ToC/side nav will be tested in the upcoming Mars article, then we can decide to include elsewhere.
